
import './globals.css'
import type { Metadata } from 'next'
import ToasterContext from './context/ToasterContext'
import Navbar from './component/Navbar'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Footer from './component/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script
        type="text/javascript"
        src="../node_modules/tw-elements/dist/js/tw-elements.umd.min.js"></Script>
      <body className={inter.className}>

        <ToasterContext />
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  )
}
